Open-Source-Spatial-Clean-Cooking-Tool/OnStove

- onsstove/onsstove.py
> chaged df for gdf in OnSSTOVE class

- .gitignore
- onsstove/onsstove.py
- onsstove/technology.py
This PR closes #32 and closes #37. It contains:
* A method `read_tech_data` under the `OnSSTOVE` class to read the `tech_specs.csv` file. This function reads the data and creates a technology for each fuel, and saves them in a `self.techs` dictionary.
* A method `__setitem__` under the `Technology` class to allow setting a parameter of the class with a dictionary notation: `technology['parameter'] = 'something`. This is used in the `read_tech_data` method.
* Changes some `Param` names from the `tech_specs` file (#32) so they match the ones in the `Technology` class.
* Removes the lines in the `technology.py` file where we created the technologies manually.
> Method to read tech specs file and create technologies dict

- onsstove/technology.py
Reading relative risk and calculating the paf value for each disease. This closes #46
> created paf

- onsstove/technology.py
Calculates RR for each disease. This closes #47.
> Creates RR

- onsstove/layer.py
- onsstove/onsstove.py
- onsstove/raster.py
This PR implements the `distance_to_electricity` method under the `OnSSTOVE` class, to calculate the proximity to HV lines, MV lines and transformers and add the result to the main geodataframe. Details about usage can be found in #38.
This PR closes #38
> Distance to electricity network

- onsstove/technology.py
reads tech and the social specs file, add morbidity and mortaltiy to  each technology. This fixes #45
> Morbidity function

- onsstove/onsstove.py
def elec_current calibrates electrified population in urban and rural (and national).
It checks if there are transofmers or MV lines and uses these first. If there are none (columns are missing) it goes with HV.
It also includes a dummy distance in case calibrated elec does not add up in urban and rural settlements.
Requires five new inputs in specs file (these are added and uplaoded to box)
Many hardcoded instances. Consider rearrangning the code to collect them all in one place for easy access? Also do we want to calibrate elec in urban and rural or only worry about national  urban/rural is dependent on our own calibration?
This fixes #41
> Added elec_current

- onsstove/technology.py
Calculates mortality for each disease and adds to corresponding technology
> Created mortality function

- onsstove/technology.py
Function calcuating discount factor and years of analysis. These are both used for all costs and benefits. This fixes #65
> discount_factor function

- onsstove/technology.py
> Created function determining discounted investment

- onsstove/technology.py
> Calcuating discounted salvage

- onsstove/technology.py
> Carbon emissions function

- onsstove/technology.py
> net_benefit

- onsstove/onsstove.py
- onsstove/raster.py
- onsstove/technology.py
> Value of time

- onsstove/onsstove.py
> Added maximum net_benefit to gdf

- onsstove/onsstove.py
- onsstove/technology.py
> Created base fuel

- Nepal runner.ipynb
- onsstove/onsstove.py
- onsstove/technology.py
This PR fixes the units of the value of time and time saved methods. This closes #110
> fixed time saved units

- onsstove/technology.py
Converted investment, O&M, salvage, fuel cost and carbon emissions to be calculated per cell. This fixes #115
> Per cell calculations

- onsstove/technology.py
> Updated LPG class

- onsstove/onsstove.py
- onsstove/technology.py
> Deaths avoided

- onsstove/onsstove.py
> Reduced emissions

- onsstove/onsstove.py
> Extract time saved per cell to each cell

- onsstove/onsstove.py
> Health costs avoided

- onsstove/onsstove.py
> Convert gdf to df and saving as csv

- onsstove/onsstove.py
> Adding admin names

- onsstove/layer.py
- onsstove/onsstove.py
> fixed function for extracting rwi

- Nepal runner.ipynb
- onsstove/technology.py
> Updated biogas function

- onsstove/onsstove.py
- onsstove/technology.py
- scripts/model_preparation.py
- snakefile.smk
This PR implements the `set_base_fuel` and the `get_clean_cooking_access` methods for the `OnSSTOVE` class. This closes #187 and closes #188
> method for average base fuel calculations

- Nepal runner.ipynb
- onsstove/onsstove.py
- onsstove/technology.py
- scripts/data_processing.py
- scripts/model_preparation.py
- scripts/model_run.py
- snakefile.smk
- Costs updated to be compared to the base fuel
- Benefits do not seem to work correctly. The benefits of technologies should be negative if they are worse than the base line (currently e.g. trad. biomass has 0 in benefits in ZAF)
> costs compared to base fuel situation

- onsstove/onsstove.py
- scripts/model_preparation.py
- scripts/model_run.py
- snakefile.smk
Added charcoal technologies to the code and also fixed a bug where the code would crash if the poverty layer was given as a polygon.
> Added Trad. charcoal and charcoal ICS + fixed poverty bug

- onstove/model.py
> Made sure that we have default values in the social specs

- LICENSE
- README.md
This PR implements a version of hydro Mini Grid technologies. These are calibrated based on the proximity and available capacity.
It also makes several enhancements to the plotting functions.
This solves part of issue #318 and solves #309, solves #305, solves #296 and solves #297, solves #294.
> Plotting enhancements and Mini Grids Technologies

- onstove/model.py
> Fix invalid value in cast for fillnan method

- onstove/_utils.py
- onstove/layer.py
- onstove/model.py
- onstove/tests/test_plot_results.py
- scripts/main_plot.tex
- scripts/merge_results.py
- scripts/model_run.py
Added more options for plotting to make things more consistent. See issue #342 for more info.
> Plotting fixes

- .gitignore
- onstove/_utils.py
- onstove/layer.py
- onstove/model.py
This PR updates documentation for several methods of the `model.py`.
> Documentation updates

- onstove/model.py
- onstove/technology.py
This PR solves wrong display units for the stats in the map, corrects the way time saved is extracted and implements collection time for LPG (based on user input not geospatial)
> fix stats units and collection time for LPG

- envs/jupyter_env.yaml
- envs/snake_env.yaml
- onstove/model.py
- onstove/technology.py
Solves bugs in inconsistent data types
> Data type bug fixes
